name: Auto Minify CSS
on: [push]
jobs:
  minify:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grant write access to contents for pushing commits
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Make root writable
        run: chmod -R u+w . || true  # Ensure root directory is writable to avoid permission issues
      - name: Minify files
        uses: nizarmah/auto-minify@v3
        with:
          directory: '.'  # Adjust to your CSS folder path if not in root (e.g., 'styles/')
          output: 'temp_dist/'  # Use a temporary folder for minified files
          overwrite: false
          css_engine: 'clean-css'
      - name: Rename and move minified CSS to root
        run: |
          mkdir -p temp_dist  # Ensure temp_dist exists
          chmod -R u+w temp_dist || true  # Make temp_dist and its files writable
          rm -f ./*.min.css  # Remove any existing .min.css in root to avoid conflicts
          for file in temp_dist/*.css; do
            if [ -f "$file" ] && [[ ! "$file" =~ \.min\.css$ ]]; then
              cp "$file" "./$(basename "${file%.css}.min.css")"
            fi
          done
          rm -rf temp_dist || true  # Clean up temporary folder, ignore errors
      - name: Commit minified files
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "Auto-minified CSS files with .min suffix in root"
