name: Auto Minify CSS
on: [push]
jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Minify files
        uses: nizarmah/auto-minify@v3
        with:
          directory: '.'  # Or your CSS folder path
          overwrite: true
          css_engine: 'clean-css'
      - name: Commit minified files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-minified CSS files"
